apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-python-python-3.8.fullname" . }}
  labels:
    {{- include "python-python-python-3.8.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "python-python-python-3.8.selectorLabels" . | nindent 4 }}
